- alias: Aqara motion sensor - reset ZHA cluster
  id: "163643543456345"
  description: ""
  trigger:
    - entity_id: binary_sensor.kit_motion_sensor
      platform: state
      from: "off"
      to: "on"
  condition:
    - condition: state
      entity_id: binary_sensor.kit_motion_sensor
      state: "on"
  action:
    - delay:
        seconds: 30
    - service: zha.set_zigbee_cluster_attribute
      data:
        ieee: 00:15:8d:00:07:58:15:07
        endpoint_id: 1
        cluster_id: 1280
        cluster_type: in
        attribute: 2
        value: 0
  mode: single
