- alias: Aqara motion sensor - reset ZHA cluster LR_1
  id: "163643543453344"
  description: ""
  trigger:
    - entity_id: binary_sensor.lr_motion_sensor_1
      platform: state
      from: "off"
      to: "on"
  condition:
    - condition: state
      entity_id: binary_sensor.lr_motion_sensor_1
      state: "on"
  action:
    - delay:
        seconds: 45
    - service: zha.set_zigbee_cluster_attribute
      data:
        ieee: 00:15:8d:00:02:e9:85:f4
        endpoint_id: 1
        cluster_id: 1280
        cluster_type: in
        attribute: 2
        value: 0
  mode: single
